[project]
name = "nomad"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "ffmpeg-python>=0.2.0",
    "pydantic-settings>=2.7.1",
    "python-telegram-bot>=21.10",
    "ultralytics>=8.3.70",
]
